on:
  workflow_dispatch:

env:
  PACKAGING_DIRECTORY: ./packaging-automation-tests
  PACKAGE_ID: MyUnlockedPackage
  TARGET_DEV_HUB: MathiasDevHub

jobs:
  create-package-version:
    name: Create package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          ref: master

      
      - name: Checkout packaging-automation-tests repository
        uses: actions/checkout@v4
        with:
          repository: mathias-moreira/packaging-automation-tests
          token: ${{ secrets.GITHUB_TOKEN }}
          path: packaging-automation-tests

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Create package version
        uses: ./
        id: create-package-version
        with:
          auth-url: ${{ secrets.AUTH_URL }}
          packaging-directory: ${{ env.PACKAGING_DIRECTORY }}
          package: ${{ env.PACKAGE_ID }}
          target-dev-hub: ${{ env.TARGET_DEV_HUB }}
          installation-key-bypass: true
          skip-validation: true
          code-coverage: false
          async-validation: false
          timeout: 10
          polling-interval: 20