name: Local Development
on:
  workflow_dispatch:

env:
  PACKAGING_DIRECTORY: ./packaging-automation-tests
  PACKAGE_NAME: MyUnlockedPackage
  TARGET_DEV_HUB: MathiasDevHub

jobs:
  create-package-version:
    name: Create package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        # Uncommment this to checkout the master branch of the current repository. If you are working on a branch, leave it commented to pick the most recent changes.
        # with:
        #   ref: master

      
      - name: Checkout packaging-automation-tests repository
        uses: actions/checkout@v4
        with:
          repository: mathias-moreira/packaging-automation-tests
          token: ${{ secrets.ACTION_PAT }}
          path: packaging-automation-tests

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      # Uncomment this to copy the sfdx-project.json on the current directory to the packaging-automation-tests directory and use it instead of the one in the salesforce project repository.
      # This is useful when you are working on the sfdx-project.json file and want to test the action with your changes.
      # - name: Copy sfdx-project.json to packaging-automation-tests directory
      #   run: |
      #     rm -rf ${{ env.PACKAGING_DIRECTORY }}/sfdx-project.json
      #     cp sfdx-project.json ${{ env.PACKAGING_DIRECTORY }}

      - name: Create package version
        uses: ./
        id: create-package-version
        with:
          auth-url: ${{ secrets.AUTH_URL }}
          packaging-directory: ${{ env.PACKAGING_DIRECTORY }}
          package-name: ${{ env.PACKAGE_NAME }}
          package-type: Unlocked
          target-dev-hub: ${{ env.TARGET_DEV_HUB }}
          installation-key-bypass: true
          skip-validation: true
          timeout: 10
          polling-interval: 20