name: PR Validation

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Commit messages (commitlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Validate commits in PR (also works for forks)
      - name: Lint commits in PR
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js

  actionlint:
    name: Workflow syntax (actionlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1
