name: PR Validation

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited]
  pull_request_target:
    branches: [master]
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Validate commits in PR (also works for forks)
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs

  actionlint:
    name: Workflow Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Actionlint
        id: actionlint
        uses: raven-actions/actionlint@v2
        with:
          files: ".github/workflows/*.yml, .github/workflows/*.yaml"
      
      - name: Actionlint Summary
        if: ${{ steps.actionlint.outputs.exit-code != 0 }}  # example usage, do echo only when actionlint action failed
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
          exit 1
